### PR TITLE
[BUG] x-cloud: should generate Vpc: Ref: VpcID 

### LINKED ISSUE #704: [BUG] x-cloud: should generate Vpc: Ref: VpcID
**Bug**
When using x-cloud: with a private namespace, the resulting Resources: entry generated contains `Vpc: x-vpc:VpcId`

It should use `Vpc: Ref: VpcId` instead.

****
1. pip install
2. cli tool
3. Docker compose file
```
x-cloudmap: # ecscomposex
  PrivateZone:
    ZoneName: foo.local
```
4. Results in:
```
Resources:
  PrivateZone:
    Properties:
      Name: foo.local
      Tags:
        - Key: CreatedByComposeX
          Value: true
        - Key: compose-x:version
          Value: 0.23.27-rc0
      Vpc: x-vpc:VpcId
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
```

**Expected behavior**
```
Resources:
  PrivateZone:
    Properties:
      Name: foo.local
      Tags:
        - Key: CreatedByComposeX
          Value: true
        - Key: compose-x:version
          Value: 0.23.27-rc0
      Vpc:
        Ref: VpcId
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
```

**Logs**
Not applicable

**Desktop (please complete the following information):**
 - OS: macOS 14.1 (Sonoma)
 - Python version: 3.10

### PR DESCRIPTION
**Pull request by thorfi**
Fixes #704

### CODE REVIEW

**Comment by thorfi** [comment]
Hi @JohnPreston ,

Same deal as the last one, tiny few lines bugfix.

**Comment by JohnPreston** [comment]
> Hi @JohnPreston ,
> 
> Same deal as the last one, tiny few lines bugfix.

Hey, thanks @thorfi 
Can you check my questions in the issue itself?

**Comment by JohnPreston** [comment]
Alright, considering that making `x-vpc::<attribute>` notation with Lookup looks like a fair bit of work, but the `VpcId` parameter will always be set to the cloudmap stack when creating a new private zone, I suppose this change makes sense and will always work.

**Review by JohnPreston — APPROVED** [review]

**Comment by JohnPreston** [comment]
@thorfi Feel free to join on [slack](https://join.slack.com/t/compose-x/shared_invite/zt-w9ly4f3k-QhqGDs57RY7WcBnLYDw_lg) as this might make exchange a little faster.
Thanks for the report and the bug fix as always,

**Pull request merged**
